apiVersion: v1
kind: Pod
metadata:
  name: speed-test
spec:
  containers:
  - name: speed-test
    image: registry-snapshot.c.dockerutv12.tuv.jordbruksverket.se/fiotest:0.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
  initContainers:
  - name: testdataprep
    image: registry-snapshot.c.dockerutv12.tuv.jordbruksverket.se/fiotest:0.1
    command: ["dd", "if=/dev/urandom", "of=/data/testing", "bs=1024", "count=1024000"]
    volumeMounts:
    - name: volv
      mountPath: /data

  restartPolicy: Never
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: speedtest-longhorn

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-longhorn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi


