apiVersion: v1
kind: Pod
metadata:
  name: speed-test
spec:
  containers:
  - name: speed-test
    image: registry-snapshot.c.dockerutv12.tuv.jordbruksverket.se/fiotest:0.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
  restartPolicy: Never
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: speedtest-xfs

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-xfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  selector:
          matchLabels:
                  source: xfs-speedtest-2021-10-10
  resources:
    requests:
      storage: 2Gi

