apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvcreator
spec:
  selector:
    matchLabels:
      app: pvcreator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pvcreator
    spec:
      serviceAccountName: kubernetes-pvcreator-controller
      containers:
      - name: pvcreator-master
        image: mireg.wr25.org/reflinkpv:0.1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/home/pvcreator/.ssh/"
          name: ssh-key
          readOnly: true
        - mountPath: "/home/pvcreator/conf.yml"
          name: pvcreator-conf
          readOnly: true
      volumes:
      - name: ssh-key
        secret:
          secretName: ssh-key
      - name: pvcreator-conf
        configMap:
          name: pvcreator-config
          items:
          - key: "conf.yml"
            path: "conf.yml"
